### ISSUE TITLE
opts is not defined

### ISSUE THREAD

**Issue by impronunciable** [LearnBoost/superagent-oauth#6]
https://github.com/LearnBoost/superagent-oauth/blob/master/superagent-oauth.js#L22

Are you planning to add opts as a extern variable for the "sign" method, a parameter for the function or can I remove it?

**Comment by rauchg** [comment]
Great global leak :D

**Comment by rauchg** [comment]
We just removed `opts`, so we should get rid of that line
https://github.com/LearnBoost/superagent-oauth/commit/d0531b41c7d386213928b108bb09b41a16141911

**Comment by rauchg** [comment]
Good catch, thanks

**Comment by impronunciable** [comment]
https://github.com/LearnBoost/superagent-oauth/pull/5
